/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AI-generated response content
 */
export type Content = string;

/**
 * Schema for a chat message response.
 * This is returned as a stream for the /chat endpoint.
 */
export interface ChatResponse {
  content: Content;
  [k: string]: unknown;
}
