/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The message content to send to the AI
 */
export type Message = string;

/**
 * Schema for a chat message request.
 * This is the primary schema used for the /chat endpoint.
 */
export interface ChatMessage {
  message: Message;
  [k: string]: unknown;
}
