/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The message content to send to the AI
 */
export type Message = string;
/**
 * The AI model to use for generation
 */
export type Model = string;
/**
 * Controls randomness in the response. Lower is more deterministic.
 */
export type Temperature = number;
/**
 * Instructions for the AI assistant's behavior
 */
export type SystemMessage = string | null;
/**
 * Optional list of previous messages in the conversation
 */
export type MessageHistory = HistoryMessage[] | null;
/**
 * The role of the message sender.
 */
export type Role = "user" | "assistant" | "system";
/**
 * The content of the message.
 */
export type Content = string;

/**
 * Extended schema for a chat request with additional parameters.
 * This can be used for more advanced chat endpoints.
 */
export interface CompleteQueryRequest {
  message: Message;
  model?: Model;
  temperature?: Temperature;
  system_message?: SystemMessage;
  message_history?: MessageHistory;
  [k: string]: unknown;
}
/**
 * Schema for a single message in the chat history.
 */
export interface HistoryMessage {
  role: Role;
  content: Content;
  [k: string]: unknown;
}
