/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A human-readable error message
 */
export type Detail = string;
/**
 * An optional error code for programmatic handling
 */
export type Code = string | null;

/**
 * Schema for error responses.
 */
export interface ErrorResponse {
  detail: Detail;
  code?: Code;
  [k: string]: unknown;
}
